### ISSUE TITLE
What is valid input for webhook-secret?

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-webhook-action#7]
I see in Marketplace the `ziti-id` param is the JSON identity config, but how is a valid value for `webhook-secret` composed?

**Comment by smilindave26** [comment]
`ziti-webhook-action` attempts to mimic GitHub webhooks ala https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks

**Comment by qrkourier** [comment]
Got it, thanks. Now I see this value is only used to add an authenticity and integrity signature as an HTTP header which the recipient may choose to use to verify the sender is in possession of the same secret string.
